services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  BR\Toolkit\:
    resource: '../Classes/*'
    exclude: ['../Classes/{Misc/DTO,Typo3/DTO,PHPUnit,Exceptions,Typo3/Routing/Aspect}']


  BR\Toolkit\Typo3\Cache\Command\CacheCommand:
    tags:
      - name: 'console.command'
        command: 'brt:cache'
        description: 'BR-Toolkit Cache Command'
        hidden: false
        schedulable: false
