name: testing
on: [push, pull_request]

jobs:
  unit-tests:
    name: "PHP Unit Tests"
    runs-on: ubuntu-20.04
    env:
      TYPO3_PATH_WEB: .Build/Web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
          tools: composer:v2
      - name: "Composer Install"
        run: "composer require typo3/minimal=${{ matrix.typo3 }}"
      - name: "Run Unit Tests"
        run: "XDEBUG_MODE=coverage .Build/bin/phpunit -c phpunit.xml --coverage-text --colors=never"
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
        typo3:
          - 9.5
          - 10.4
          - 11.5
        exclude:
          - typo3: 11.5
            php: 7.2
          - typo3: 11.5
            php: 7.3
            
